import { Context } from "probot";
import { DocSuggestion } from "../types/suggestion";

/**
 * Post documentation suggestions as PR comment
 */
export async function postDocumentationSuggestions(
  context: Context,
  pr: any,
  suggestions: DocSuggestion[]
): Promise<void> {
  const payload = context.payload as any;
  const repository = payload.repository;

  const commentBody = formatSuggestionsComment(suggestions);

  await context.octokit.rest.issues.createComment({
    owner: repository.owner.login,
    repo: repository.name,
    issue_number: pr.number,
    body: commentBody,
  });
}

/**
 * Format suggestions as markdown comment
 */
function formatSuggestionsComment(suggestions: DocSuggestion[]): string {
  const parts: string[] = [];

  parts.push("## 📝 ReadmeMuse: Documentation Update Suggestions");
  parts.push("");
  parts.push("I've analyzed your PR and found potential documentation updates:");
  parts.push("");

  for (const suggestion of suggestions) {
    parts.push(`### ${suggestion.filePath}`);
    parts.push("");
    parts.push(`**Summary:** ${suggestion.summary}`);
    parts.push("");
    parts.push(`**Reasoning:** ${suggestion.reasoning}`);
    parts.push("");
    parts.push("<details>");
    parts.push("<summary>📋 View suggested diff</summary>");
    parts.push("");
    parts.push("```diff");
    parts.push(suggestion.diffPatch);
    parts.push("```");
    parts.push("");
    parts.push("</details>");
    parts.push("");
    parts.push("---");
    parts.push("");
  }

  parts.push("*💡 These suggestions are generated by ReadmeMuse to help keep your documentation in sync with code changes.*");
  parts.push("");
  parts.push("*Click on the diff patches above to view the suggested changes. You can apply them manually or use them as a guide.*");

  return parts.join("\n");
}
